default_language_version:
  node: latest
exclude: '\.snap|node_modules$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
        exclude: |
          (?x)^(
              develop-docs/application/config.mdx|
              develop-docs/integrations/github.mdx|
              develop-docs/self-hosted/sso.mdx
          )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: flake8
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/getsentry/pre-commit-hooks
    rev: f3237d2d65af81d435c49dee3593dc8f03d23c2d
    hooks:
      - id: prettier
        entry: node_modules/.bin/prettier
      - id: eslint
        entry: node_modules/.bin/eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: node
        types: [javascript, typescript]
        files: \.(js|ts|jsx|tsx)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: node
        types: [javascript, typescript, json, css, scss, less, html, md, yaml, graphql]
